Repository DSACMS/repo-scaffolder, pull requests merged in 2024-11, with the labels that each got.

#197 Fixed Multi-Select Fields Formatting and Fixed Broken Link
  tier0/{{cookiecutter.project_slug}}/README.md
  tier1/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
  tier1/{{cookiecutter.project_slug}}/README.md
  tier2/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
  tier3/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
  tier4/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
Labels: bug

#191 Docs: Created GH Action workflow to generated pdfs of checklist from markdown files
  .github/workflows/checklistMarkdownToPDF.yml
  tier1/checklist.md
  tier1/checklist.pdf
  tier2/checklist.md
  tier2/checklist.pdf
  tier3/checklist.md
  tier3/checklist.pdf
  tier4/checklist.md
  tier4/checklist.pdf
Labels: documentation, enhancement, automation

#199 Cookiecutter: Updated Cookiecutter to use latest release 2.6.0
  requirements.txt
Labels: cookiecutter
