Repository DSACMS/repo-scaffolder, pull requests merged in 2025-04, with the labels that each got.

#283 Cookiecutter: Added pre_prompt.sh containing intro to using repo-scaffolder tool
  tier0/hooks/pre_prompt.sh
  tier1/hooks/pre_prompt.sh
  tier2/hooks/pre_prompt.sh
  tier3/hooks/pre_prompt.sh
  tier4/hooks/pre_prompt.sh
Labels: enhancement, automation, cookiecutter

#285 Update README.md - closes #220
  README.md
Labels: bug, documentation

#289 Cookiecutter: Updated codeowners cookiecutter prompt
  tier2/cookiecutter.json
  tier3/cookiecutter.json
  tier4/cookiecutter.json
Labels: enhancement, cookiecutter
